### ISSUE TITLE
winpenguins not working in windows 10 homex64 but working fine in windows 10 enterprise x64. 

### ISSUE THREAD

**Issue by sarashvi** [ricky65/WinPenguins#2]
In windows 10 home x64 taskbar icon is there but no penguins on screen and options from taskbar icon don't work. I installed this from Microsoft store as well as installed and tried from other website and also portable version from portableapps.com

**Comment by ricky65** [comment]
Previously people have had problems with penguins not displaying on screen where they have an NVIDIA Graphics Card and NVIDIA GeForce Overlay enabled. Could this be the issue for you?

**Comment by sarashvi** [comment]
Sorry for delay in replying. No. I have Intel HD family integrated graphic card. Further in same laptop (Acer Aspire R& 572 windows 10) I have dual boot system with windows Home 10 x64 and windows enterprise 10 x64 installed in 2 partitions of hard drive. So basically SAME graphic card is used by each W Home & W Enterprise systems. Curiously, in Win Enterprise 10 x64, winpenguins works perfectly However in Win Home 10 x64, winpenguins installs OK and right click on icon in task bar opens options/setting etc too. But no penguins are displayed on screen. Choices in options can be selected byt they dont have any effect as no penguines are displayed on screen in Home edition. In Enterprise boot, all options work and penguines also are displayed on screed as per selected choices.

**Comment by sarashvi** [comment]
any solution on this please

**Comment by ricky65** [comment]
My guess is that there is an app installed with an invisible Window on your Home partition that is not installed on your Enterprise partition. I would look through all the Startup Apps (Settings -> Startup Apps or Task Manager->Startup Tab), disabling each in turn to try and identify the culprit.

**Comment by sarashvi** [comment]
It was solved as per your suggestion. You were absolutely right. I disabled all startup items and winpenguins started. Thereafter one by one I verified each startup app. The culprit was a screen dimmer app, which I removed.. Winpenguins is running fine now. Thanks for your support.

**Comment by sarashvi** [comment]
Problem solved.

**Comment by ricky65** [comment]
ddsd

**Comment by ricky65** [comment]
I'm glad you resolved the problem. Thanks for downloading WinPenguins!
